/**
 Erases the target disk and leaves the new root mounted at `/mnt`.

 @module
 */

import { tagged, } from '@monochromatic-dev/module-logger';

import {
  assertTargetDisk,
  type LsblkReport,
} from './disk-guard.ts';
import type { Machine, } from './machine.ts';
import {
  type Shell,
  TARGET_ROOT,
} from './shell.ts';

/**
 Subvolumes created on the root filesystem.

 Only `@` is snapshotted.
 `/home`,
 `/root`,
 and `/srv` are plain directories inside it,
 so every snapshot of `/` is a coupled root and home pair.
 The others hold regenerable data or logs that must survive a rollback.
 */
export const SUBVOLUMES = ['@', '@cache', '@log', '@tmp',] as const;

/**
 Name of the LUKS mapping while the installer works on the target.

 It differs from the boot-time name on purpose:
 an installed CachyOS used as the installer host already has a mapping called `root`,
 and the installed system's kernel command line names its own mapping.
 */
const INSTALL_MAPPING = 'labwc-config-target';

/** Opened LUKS mapping that holds the root Btrfs filesystem during installation. */
const ROOT_MAPPER = `/dev/mapper/${INSTALL_MAPPING}`;

/** Mount options shared by every root subvolume. */
export const BTRFS_OPTIONS = 'noatime,compress=zstd,discard=async';

/** ESP size; limine-snapper-sync stores each snapshot's kernels there. */
const ESP_SIZE = '+4G';

/** Where each unsnapshotted subvolume is mounted inside the installed root. */
const DETACHED_MOUNTS: Readonly<Record<Exclude<typeof SUBVOLUMES[number], '@'>, string>> = {
  '@cache': '/var/cache',
  '@log': '/var/log',
  '@tmp': '/var/tmp',
};

/**
 Names a partition of the target by its by-id link.

 @param machine - target description
 @param number - partition number
 @returns stable partition link that udev creates after partitioning
 @example
 ```ts
 const esp = partitionOf({ machine, number: 1, },);
 ```
 */
export function partitionOf({ machine, number, }: { readonly machine: Machine; readonly number: number; },): string {
  return `${machine.targetDisk}-part${number}`;
}

/**
 Refuses to continue unless the target is an idle whole disk.

 @param machine - target description
 @param shell - side effects
 @throws {UnsafeTargetDiskError} when the disk or anything on it is mounted or mapped
 @example
 ```ts
 await checkTargetDisk({ machine, shell, },);
 ```
 */
async function checkTargetDisk({ machine, shell, }: { readonly machine: Machine; readonly shell: Shell; },): Promise<void> {
  const devicePath = (await shell.capture({
    description: 'resolve the target disk link',
    argv: ['readlink', '--canonicalize-existing', machine.targetDisk,],
  },)).trim();
  const report = JSON.parse(
    await shell.capture({
      description: 'list block devices and their mounts',
      argv: ['lsblk', '--json', '--output', 'PATH,TYPE,MOUNTPOINTS',],
    },),
  ) as LsblkReport;
  assertTargetDisk({ lsblk: report, devicePath, },);
}

/**
 Erases the target,
 creates the ESP and the LUKS2 container,
 creates the Btrfs subvolumes,
 and mounts the installed layout under `/mnt`.

 @param machine - target description
 @param shell - side effects
 @param luksPassphrase - temporary passphrase, passed on standard input
 @param luksUuid - UUID for the LUKS header, generated by the caller so the kernel command line is known in advance
 @throws {UnsafeTargetDiskError} before any write when the target is in use
 @throws {CommandFailedError} when a command fails
 @example
 ```ts
 await prepareDisk({ machine, shell, luksPassphrase, luksUuid: crypto.randomUUID(), },);
 ```
 */
export async function prepareDisk({ machine, shell, luksPassphrase, luksUuid, }: {
  readonly machine: Machine;
  readonly shell: Shell;
  readonly luksPassphrase: string;
  readonly luksUuid: string;
},): Promise<void> {
  const l = tagged({ tag: prepareDisk.name, },);
  await checkTargetDisk({ machine, shell, },);
  l.info(`erasing ${machine.targetDisk}`,);

  const disk = machine.targetDisk;
  const esp = partitionOf({ machine, number: 1, },);
  const luks = partitionOf({ machine, number: 2, },);
  await shell.run({ description: 'erase filesystem signatures', argv: ['wipefs', '--all', '--force', disk,], },);
  await shell.run({ description: 'erase the partition tables', argv: ['sgdisk', '--zap-all', disk,], },);
  await shell.run({
    description: 'create the ESP and the LUKS partition',
    argv: [
      'sgdisk',
      `--new=1:0:${ESP_SIZE}`,
      '--typecode=1:ef00',
      '--change-name=1:ESP',
      '--new=2:0:0',
      '--typecode=2:8309',
      '--change-name=2:cryptroot',
      disk,
    ],
  },);
  await shell.run({ description: 'reread the partition table', argv: ['partprobe', disk,], },);
  await shell.run({ description: 'wait for partition links', argv: ['udevadm', 'settle',], },);
  await shell.run({ description: 'format the ESP', argv: ['mkfs.fat', '-F', '32', '-n', 'ESP', esp,], },);

  await shell.run({
    description: 'format the LUKS2 container',
    argv: [
      'cryptsetup',
      'luksFormat',
      '--type',
      'luks2',
      '--batch-mode',
      '--label',
      'cryptroot',
      `--uuid=${luksUuid}`,
      '--key-file=-',
      luks,
    ],
    stdin: luksPassphrase,
  },);
  // --persistent stores allow-discards in the LUKS2 header, so every later unlock keeps TRIM.
  await shell.run({
    description: 'open the LUKS2 container',
    argv: ['cryptsetup', 'open', '--allow-discards', '--persistent', '--key-file=-', luks, INSTALL_MAPPING,],
    stdin: luksPassphrase,
  },);

  await shell.run({ description: 'create the Btrfs filesystem', argv: ['mkfs.btrfs', '--force', '--label', 'cachyos', ROOT_MAPPER,], },);
  await shell.run({ description: 'mount the Btrfs top level', argv: ['mount', ROOT_MAPPER, TARGET_ROOT,], },);
  for (const subvolume of SUBVOLUMES) {
    await shell.run({
      description: `create Btrfs subvolume ${subvolume}`,
      argv: ['btrfs', 'subvolume', 'create', `${TARGET_ROOT}/${subvolume}`,],
    },);
  }
  await shell.run({ description: 'unmount the Btrfs top level', argv: ['umount', TARGET_ROOT,], },);
  await shell.run({
    description: 'mount @ as the installed root',
    argv: ['mount', '--options', `${BTRFS_OPTIONS},subvol=/@`, ROOT_MAPPER, TARGET_ROOT,],
  },);
  const detached = Object.entries(DETACHED_MOUNTS,);
  await shell.run({
    description: 'create mount points',
    argv: ['mkdir', '--parents', ...detached.map(([, path,],) => `${TARGET_ROOT}${path}`), `${TARGET_ROOT}/boot`,],
  },);
  for (const [subvolume, path,] of detached) {
    await shell.run({
      description: `mount ${subvolume} at ${path}`,
      argv: ['mount', '--options', `${BTRFS_OPTIONS},subvol=/${subvolume}`, ROOT_MAPPER, `${TARGET_ROOT}${path}`,],
    },);
  }
  await shell.run({
    description: 'mount the ESP readable only by root',
    argv: ['mount', '--options', 'umask=0077', esp, `${TARGET_ROOT}/boot`,],
  },);
  l.info('target root mounted',);
}
