Gdk/WindowScalingFactor 2
Gdk/UnscaledDPI 98304
Xft/DPI 196608
Gtk/CursorThemeSize 48
Gtk/CursorThemeName "breeze_cursors"
Net/ThemeName "Breeze-Dark"
Net/IconThemeName "breeze-dark"
Xft/Antialias 1
Xft/HintStyle "hintslight"
