[Service]
ExecStart=
ExecStart=/usr/bin/xwayland-satellite :12
ExecStartPost=/usr/bin/systemctl --user set-environment DISPLAY=:12
ExecStartPost=-/usr/bin/dbus-update-activation-environment DISPLAY=:12
